name: Test-Less
version: 0.10
abstract: Test Categorization and Subset Execution
author: Brian Ingerson <ingy@cpan.org>
license: perl
distribution_type: module
requires:
  perl: 5.6.1
  Test::Harness: 2.46
  Test::Chunks: 0.36
  Spiffy: 0.24
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
